name: Update README
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update README
        run: python3 scripts/update_readme.py      
      - name: Push changes
        run: |
          git add README.md
          if ! git diff --cached --quiet; then
            git config user.name "Sunil Pandey"
            git config user.email "64631561+sunilbpandey@users.noreply.github.com"
            git commit -m "Update README.md"
            git push
          fi
